# Generated by Django 3.2.4 on 2021-09-29 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='client_logos/', verbose_name='Brend logosi')),
                ('br_name', models.CharField(max_length=50, verbose_name='Brend nomi')),
                ('theme', models.CharField(max_length=50, verbose_name='rangi')),
                ('link', models.CharField(max_length=50, unique=True, verbose_name='linki')),
                ('rates', models.PositiveIntegerField(default=0, verbose_name='rates')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='link nomi')),
                ('link', models.CharField(max_length=150, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='saver', to='accounts.saved')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
