# Generated by Django 3.2.4 on 2021-09-29 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='product',
            field=models.ManyToManyField(related_name='saved', to='main.Product'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='rated_users',
            field=models.ManyToManyField(blank=True, related_name='rates', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='client', to='accounts.Links'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
