# Generated by Django 3.2.4 on 2021-09-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='nomi')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F,I,SH')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Elektron pochta')),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mavzu')),
                ('phone', models.CharField(max_length=20, verbose_name='Telfon raqami')),
                ('message', models.TextField(verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product_images/', verbose_name='rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('link', models.CharField(max_length=50, unique=True, verbose_name='link')),
                ('content', models.TextField(verbose_name='tarif')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='narxi')),
                ('old_price', models.PositiveIntegerField(default=0, verbose_name='eski narxi')),
                ('for_slider', models.BooleanField(verbose_name='birinchiga')),
                ('for_duel', models.BooleanField(verbose_name='ikkitalikga')),
                ('for_big', models.BooleanField(verbose_name='kattaga')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
                ('images', models.ManyToManyField(related_name='product', to='main.Images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.userprofile')),
            ],
        ),
    ]
