# Generated by Django 3.2 on 2021-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Banner rasmi')),
                ('title', models.TextField(verbose_name='Banner matni')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='rasmi1'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='rasmi2'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='rasmi3'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='rasmi4'),
        ),
    ]
