# Generated by Django 3.2 on 2021-09-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210929_1617'),
        ('main', '0002_auto_20210929_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.clientuser'),
            preserve_default=False,
        ),
    ]
